config/routes.rb
PhotoBlog::Application.routes.draw do
  resources :markdowns, only: %i[edit update]
  controller :session do
    get '/login' => :new
    post '/login' => :create
  end

  get '/:key' => 'application#markdown', as: :root_markdown, constraints: Markdown::PagesConstraint
  resources :posts, only: %i[index create show edit update destroy], path: "" do
    member do
      patch :toggle_publish
    end
  end
  root 'posts#index'
end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug

  include HasMarkdown

  field :title, default: "Post Title"
  field :description
  field :tags
  field :date, type: Date, default: -> { Date.today }
  field :place
  field :address

  field :markdown, default: "A post is just the beginning."
  field :footnote_text

  field :published_at, type: ActiveSupport::TimeWithZone
  field :published, type: Boolean, default: false
  field :publish_order, type: Integer

  CROP_TYPES = %i[x y w h]
  CROP_ATTRIBUTES = CROP_TYPES.map { |coord| "crop_#{coord}".to_sym }
  CROP_ATTRIBUTES.each { |attribute| field attribute, type: BigDecimal }
  RATIO = Rational(14, 3)
  TO_CROP_WIDTH = 345
  field :carrierwave_dimensions, type: Hash, default: {}
  mount_uploader :photo, PhotoUploader

  slug :title do |post|
    post.slug_builder.to_url(replace_whitespace_with: "_")
  end
  METADATA_FIELDS = %i[title description date tags place address]

  scope :published, -> { where(published: true).desc(:publish_order) }

  before_update do
    if crop_changed?
      photo.recreate_versions!(:index)
    end
  end

  METADATA_BREAK = "=========="
  FOOTNOTES_BREAK = "=== Footnotes ==="
  CITE_REGEX = /---|\u2014/
  def text=(text)
    self.metadata, content = text.split(METADATA_BREAK).map(&:strip)
    self.markdown, self.footnote_text = content.split(FOOTNOTES_BREAK).map(&:strip)
  end
  def text
    post_string = []
    METADATA_FIELDS.each_with_index do |field, index|
      post_string << "#{field.to_s.titleize}: #{
      field == :description ? attributes[field] : send(field)
      }\n"
      if index % 2 == 1 && index != METADATA_FIELDS.size - 1
        post_string << "\n"
      end
    end
    post_string << "\n#{METADATA_BREAK}\n\n" << markdown << "\n\n\n#{FOOTNOTES_BREAK}\n" << footnote_text
    post_string.join
  end

  def metadata=(metadata)
    metadata.each_line do |line|
      line = line.strip
      unless line.empty?
        key, value = line.split(":").map(&:strip)
        key.downcase!
        if METADATA_FIELDS.include? key.to_sym
          if key == "date"
            value = Date.new(*value.split("-").map(&:to_i))
          end
          send("#{key}=", value)
        end
      end
    end
  end

  def footnote_text
    super || ""
  end

  def has_content?
    markdown && !!markdown.index(/\r\n/)
  end

  def toggle_publish!
    if published
      update_attributes(published_at: nil,
                        publish_order: nil,
                        published: false)
      self.class.published.reverse.each_with_index do |post, index|
        post.update_attribute :publish_order, index
      end
    else
      update_attributes(published_at: Time.zone.now,
                        publish_order: self.class.published.size,
                        published: true)
    end
  end

  def adjacent(change=nil)
    @adjacent ||= if publish_order
                    adjacent = {}
                    [-1, 1].each do |change|
                      adjacent[change] = self.class.where(publish_order: publish_order + change).first
                    end
                    adjacent
                  else
                    {}
                  end
    if change.blank?
      @adjacent.values
    else
      @adjacent[change]
    end
  end

  def locale
    address && address.match(/japan/i) ? :jp : :kr
  end

  def crop_changed?
    !(changed & self.class::CROP_ATTRIBUTES.map(&:to_s)).empty?
  end
  def recreate_versions!
    photo.recreate_versions!
    save
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authorize, except: %i[index show]

  def index
    @posts = authenticated? ? Post.all.desc(:updated_at) : Post.published.to_a
  end

  def show
    @post = Post.find(params[:id])

    if html? && user_agent.mobile?
      index
    end
  end

  def create
    if params[:post]
      post = Post.create(create_params)
      redirect_to edit_post_path post
    else
      redirect_to posts_path
    end
  end

  def edit
    @post = Post.find(params[:id])
    js params: { ratio: Post::RATIO.to_f, cached_coords: @post.coords }
  end

  def update
    post = Post.find(params[:id])
    post.update_attributes update_params
    redirect_to edit_post_path post
  end

  def destroy
    Post.find(params[:id]).destroy
    redirect_to posts_path
  end

  def toggle_publish
    post = Post.find(params[:id])
    post.toggle_publish!
    redirect_to edit_post_path post
  end

  protected
  def create_params
    params.require(:post).permit(:photo)
  end

  def update_params
    params.require(:post).permit(*(%i[text] + Post::CROP_ATTRIBUTES))
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def direction_arrow(change)
    post = @post.adjacent change
    if post
      content_tag :div, class: Post.direction(change) do
        content_tag :div, class: "container" do
          link_to image_tag("arrows/#{Post.direction(change)}.png"), post_path(post), data: { behavior: "photo_box_#{Post.direction(change)}" }
        end
      end
    end
  end
end

app/views/posts/_content.html.erb
<% cache ([@post, user_agent.mobile?] + @post.adjacent) do %>
    <div class="content">
      <div class="markdown">
        <%= @post.markdown_html %>
      </div>

      <% unless @post.footnotes.empty? %>
          <div class="footnotes">
            <ol>
              <%= @post.footnote_points %>
            </ol>
          </div>
      <% end %>
    </div>
    <% unless user_agent.mobile? %>
        <div class="next_prev">
          <%= render "direction_footer", change: -1 %>
          <%= render "direction_footer", change: 1 %>
        </div>
    <% end %>
    <%= render "layouts/comments" %>
<% end %>

app/views/posts/_direction_footer.html.erb
<% post = @post.adjacent change %>

<% if post %>
    <%= link_to post, class: Post.direction(change) do %>
        <div class="title">
          <%= post.title %>
        </div>
        <div class="description">
          <%= post.description %>
        </div>
        <%= image_tag "arrows/text_#{Post.direction(change)}.svg", class: "arrow" %>
    <% end %>
<% else %>
    <div>&nbsp;</div>
<% end %>

app/views/posts/_photo_box.html.erb
<div class="photo_box" data-behavior="photo_box">
  <div class="ui">
    <%= direction_arrow -1 %>
    <%= direction_arrow 1 %>

    <%= render "summary_content", post: @post %>
  </div>

  <div class="photo">
    <%= picturefill @post.photo %>
  </div>
</div>
<script>Behavior.photo_box();</script>

app/views/posts/_photoswipe.html.erb
<div class="popup" data-behavior="popup">
  <header>
    <div class="space"></div>
    <%= link_to image_tag("close_x.svg", class: "close_x"), "#close_x", data: { behavior: "close_x" }, class: "close_link" %>
    <div class="title"><div data-behavior="popup_title"></div></div>
  </header>
  <div class="popup_content container_outer" data-behavior="popup_content"></div>
</div>

<div data-behavior="swipe" data-index="<%= @post.publish_order %>" class="swipe">
  <ul>
    <% @posts.reverse.each do |post| %>
        <% loaded = @post.id == post.id %>
        <%= content_tag :li, data: { path: post_path(post), title: post.title, loaded: loaded }  do %>
            <% if loaded %>
                <%= render "photoswipe_content" %>
            <% else %>
                <div class="center_container">
                  <%= render "layouts/spinner" %>
                </div>
            <% end %>
        <% end %>
    <% end %>
  </ul>
</div>

app/views/posts/_photoswipe_content.html.erb
<% cache @post do %>
    <div data-behavior="pinch_zoom" class="pinch_zoom">
      <div class="center_container">
        <%= picturefill @post.photo %>
      </div>
    </div>
    <%= render "summary_content" %>
<% end %>

app/views/posts/_post.html.erb
<% cache post do %>
    <%= link_to post_path(post), data: { read_url: post_path(post), edit_url: edit_post_path(post) } do %>
        <article class="post">
          <%= picturefill post.photo.index.gray %>
          <%= picturefill post.photo.index, class: "color" %>

          <header>
            <div>
              <div class="date"><%= post.localized_date %></div>
              <h3><%= post.title %></h3>
            </div>
          </header>
        </article>
    <% end %>
<% end %>

app/views/posts/_summary_content.html.erb
<div class="container_outer summary_content_container" data-behavior="summary_content_container">
  <div class="container">
    <div class="space">
      <div class="summary_content">
        <div>
          <%= @post.localized_date %>
          <h2><%= @post.title %></h2>
          <div class="place"><%= @post.location %></div>
          <%= @post.snippet %>
        </div>
        <%= @post.read_story %>
      </div>
      <%= @post.comment_box %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<% set_title "Edit #{@post.title}" %>

<%= render "layouts/logo_header" %>

<div class="preview">
  <%= image_tag @post.photo.desktop, data: { behavior: "crop_preview" } %>
</div>

<div class="container_outer">
  <section class="main">
    <%= form_for @post, html: { class: "left", data: { behavior: "crop_form" }} do |f| %>
        <% Post::CROP_ATTRIBUTES.each do |attribute| %>
            <%= f.hidden_field attribute %>
        <% end %>
        <%= f.label :text %><br />
        <%= f.text_area :text %>
        <%= submit_tag "Update" %>
    <% end %>

    <div class="right">
      <%= image_tag @post.photo.to_crop, data: { behavior: "crop" } %>

      <%= link_to "Preview", post_path(@post), class: "preview_link" %>
      <div>
        <%= link_to @post.published ? "Unpublish" : "Publish", toggle_publish_post_path(@post), method: :patch %>
      </div>
      <%= link_to "Destroy", post_path(@post), method: :delete, data: { confirm: "Destroy '#{@post.title}'?" } %>

      <%= text_area_tag :facebook_summary, @post.facebook_summary, class: "facebook_summary", readonly: true, data: { behavior: "select_all" }%>
    </div>
  </section>
</div>

app/views/posts/index.html.erb
<% set_title %>
<% flowtype %>
<%= render "layouts/header" %>

<section class="post" data-behavior="read_mode_container">
  <%= render @posts %>
</section>

app/views/posts/show.html.erb
<% set_title @post.title %>
<% flowtype :read %>
<% social_networks @post %>

<%= render "layouts/logo_header" %>

<% if user_agent.mobile? %>
    <%= render "photoswipe" %>
<% else %>
    <% cache ([@post, user_agent.mobile?] + @post.adjacent) do %>
        <%= render "photo_box" %>
        <div class="container_outer">
          <section id="main_content" class="main">
            <% if @post.has_content? %>
                <%= render "content" %>
            <% else %>
                <%= render "layouts/comments" %>
            <% end %>
          </section>
        </div>
    <% end %>
<% end %>