config/routes.rb
PhotoBlog::Application.routes.draw do
  resources :markdowns, only: %i[edit update]
  controller :session do
    get '/login' => :new
    post '/login' => :create
  end

  get '/:key' => 'application#markdown', as: :root_markdown, constraints: Markdown::PagesConstraint
  resources :posts, only: %i[index create show edit update destroy], path: "" do
    member do
      patch :toggle_publish
    end
  end
  root 'posts#index'
end

app/views/layouts/_comments.html.erb
<div id="comments" class="comments">
  <div id="disqus_thread"></div>
</div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'travelcaptions'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/layouts/_disqus.html.erb
<div id="comments">
  <div id="disqus_thread"></div>
</div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = '1kansai'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/layouts/_google_analytics.html.erb
<script>
    <% if Rails.env.production? %>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-52431310-1', 'auto');
    ga('send', 'pageview');
    function page_view(path) {
        ga('send', 'pageview', path);
    }
    <% else %>
    function page_view(path) {
        console.log("Analytics: " + path);
    }
    <% end %>
</script>

app/views/layouts/_head.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<%= render "layouts/head/typekit" %>

<%= stylesheet_link_tag "//cdnjs.cloudflare.com/ajax/libs/normalize/2.1.3/normalize.min.css" %>
<%= stylesheet_link_tag "application", media: "all" %>

<%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" %>

<% if user_agent.mobile? %>
    <%= render "layouts/head/mobile" %>
<% else %>
    <%= stylesheet_link_tag "desktop", media: "all" %>
    <%= render "layouts/head/admin" %>
<% end %>

<script>is_mobile = <%= user_agent.mobile? %>;</script>
<% content_for :load_last do %>
    <%= render "layouts/google_analytics" %>
    <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.0/jquery.cookie.min.js" %>
    <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/jquery-scrollTo/1.4.7/jquery.scrollTo.min.js" %>
<% end %>
<%= javascript_include_tag "application" %>

<%= render "layouts/head/identity" %>

<%= csrf_meta_tags %>

app/views/layouts/_header.html.erb
<div class="notice">
  Bonus content on the <%= link_to "Facebook", "http://www.facebook.com/travelcaptions" %> page.
</div>

<% cache authenticated? do %>
    <div class="container_outer">
      <header class="main">
        <h1><%= link_to site_name, root_path %></h1>
        <div class="right">
          <% if authenticated? && action_name == "index" %>
              <%= form_for Post.new, html: { multipart: true } do |f| %>
                  <%= f.file_field :photo %>
                  <%= f.submit %>
              <% end %>
              <%= link_to "", "#read_mode", data: { behavior: "read_mode" } %>
          <% end %>
          <%= link_to "About", root_markdown_path(:about) %>

          <div class="social">
            <% %i[facebook twitter].each do |social_network| %>
                <%= link_to image_tag("social/#{social_network}.svg"),
                            "http://www.#{social_network}.com/travelcaptions",
                            target: "_blank" %>
            <% end %>
          </div>
        </div>
      </header>
    </div>
<% end %>

app/views/layouts/_invisible_header.html.erb
<header class="invisible">
  <%= render "layouts/header" %>
</header>

app/views/layouts/_logo_header.html.erb
<h1 class="logo"><%= link_to image_tag("logo.svg"), root_path %></h1>

app/views/layouts/_spinner.html.erb
<div class="spinner balls">
  <% 5.times.each do %><div></div><% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render "layouts/head" %>
</head>
<body data-controller="<%= jaction.controller_path %>" data-action="<%= jaction.action_name %>">
<%= yield :flowtype %>

<%= yield %>

<%= yield :load_last %>
</body>
</html>